export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          date_of_birth: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          preferred_language: string;
          is_verified: boolean;
          verification_documents: any;
          privacy_settings: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          preferred_language?: string;
          is_verified?: boolean;
          verification_documents?: any;
          privacy_settings?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          preferred_language?: string;
          is_verified?: boolean;
          verification_documents?: any;
          privacy_settings?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      drivers: {
        Row: {
          id: string;
          license_number: string;
          license_expiry: string;
          background_check_status: 'pending' | 'approved' | 'rejected' | 'expired';
          rating: number;
          total_rides: number;
          is_active: boolean;
          current_location: any;
          status: 'available' | 'busy' | 'offline';
          documents: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          license_number: string;
          license_expiry: string;
          background_check_status?: 'pending' | 'approved' | 'rejected' | 'expired';
          rating?: number;
          total_rides?: number;
          is_active?: boolean;
          current_location?: any;
          status?: 'available' | 'busy' | 'offline';
          documents?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          license_number?: string;
          license_expiry?: string;
          background_check_status?: 'pending' | 'approved' | 'rejected' | 'expired';
          rating?: number;
          total_rides?: number;
          is_active?: boolean;
          current_location?: any;
          status?: 'available' | 'busy' | 'offline';
          documents?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          driver_id: string;
          make: string;
          model: string;
          year: number;
          color: string;
          license_plate: string;
          vehicle_type: 'sedan' | 'hatchback' | 'suv' | 'bike' | 'auto';
          fuel_type: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'cng';
          is_electric: boolean;
          capacity: number;
          insurance_expiry: string;
          registration_expiry: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          make: string;
          model: string;
          year: number;
          color: string;
          license_plate: string;
          vehicle_type: 'sedan' | 'hatchback' | 'suv' | 'bike' | 'auto';
          fuel_type: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'cng';
          is_electric?: boolean;
          capacity?: number;
          insurance_expiry: string;
          registration_expiry: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          driver_id?: string;
          make?: string;
          model?: string;
          year?: number;
          color?: string;
          license_plate?: string;
          vehicle_type?: 'sedan' | 'hatchback' | 'suv' | 'bike' | 'auto';
          fuel_type?: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'cng';
          is_electric?: boolean;
          capacity?: number;
          insurance_expiry?: string;
          registration_expiry?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      rides: {
        Row: {
          id: string;
          user_id: string;
          driver_id: string | null;
          vehicle_id: string | null;
          pickup_location: string;
          pickup_coordinates: any;
          destination_location: string;
          destination_coordinates: any;
          ride_type: 'standard' | 'premium' | 'shared' | 'bike' | 'auto';
          status: 'requested' | 'matched' | 'accepted' | 'started' | 'completed' | 'cancelled';
          fare_estimate: number;
          final_fare: number | null;
          distance_km: number | null;
          duration_minutes: number | null;
          payment_method: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          payment_status: 'pending' | 'completed' | 'failed' | 'refunded';
          ride_coins_earned: number;
          ride_coins_used: number;
          carbon_credits_earned: number;
          privacy_mode: boolean;
          emergency_contacts_notified: boolean;
          route_data: any;
          safety_metrics: any;
          requested_at: string;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          pickup_location: string;
          pickup_coordinates: any;
          destination_location: string;
          destination_coordinates: any;
          ride_type?: 'standard' | 'premium' | 'shared' | 'bike' | 'auto';
          status?: 'requested' | 'matched' | 'accepted' | 'started' | 'completed' | 'cancelled';
          fare_estimate: number;
          final_fare?: number | null;
          distance_km?: number | null;
          duration_minutes?: number | null;
          payment_method?: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          payment_status?: 'pending' | 'completed' | 'failed' | 'refunded';
          ride_coins_earned?: number;
          ride_coins_used?: number;
          carbon_credits_earned?: number;
          privacy_mode?: boolean;
          emergency_contacts_notified?: boolean;
          route_data?: any;
          safety_metrics?: any;
          requested_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          pickup_location?: string;
          pickup_coordinates?: any;
          destination_location?: string;
          destination_coordinates?: any;
          ride_type?: 'standard' | 'premium' | 'shared' | 'bike' | 'auto';
          status?: 'requested' | 'matched' | 'accepted' | 'started' | 'completed' | 'cancelled';
          fare_estimate?: number;
          final_fare?: number | null;
          distance_km?: number | null;
          duration_minutes?: number | null;
          payment_method?: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          payment_status?: 'pending' | 'completed' | 'failed' | 'refunded';
          ride_coins_earned?: number;
          ride_coins_used?: number;
          carbon_credits_earned?: number;
          privacy_mode?: boolean;
          emergency_contacts_notified?: boolean;
          route_data?: any;
          safety_metrics?: any;
          requested_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_wallets: {
        Row: {
          id: string;
          user_id: string;
          balance: number;
          ride_coins: number;
          carbon_credits: number;
          total_earned: number;
          total_spent: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          balance?: number;
          ride_coins?: number;
          carbon_credits?: number;
          total_earned?: number;
          total_spent?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          balance?: number;
          ride_coins?: number;
          carbon_credits?: number;
          total_earned?: number;
          total_spent?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          user_id: string;
          wallet_id: string;
          type: 'credit' | 'debit';
          category: 'ride_payment' | 'wallet_topup' | 'refund' | 'bonus' | 'cashback' | 'ride_coins_redemption';
          amount: number;
          ride_coins_change: number;
          carbon_credits_change: number;
          description: string;
          reference_id: string | null;
          payment_method: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          transaction_id: string | null;
          status: 'pending' | 'completed' | 'failed' | 'cancelled';
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          wallet_id: string;
          type: 'credit' | 'debit';
          category: 'ride_payment' | 'wallet_topup' | 'refund' | 'bonus' | 'cashback' | 'ride_coins_redemption';
          amount: number;
          ride_coins_change?: number;
          carbon_credits_change?: number;
          description: string;
          reference_id?: string | null;
          payment_method?: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          transaction_id?: string | null;
          status?: 'pending' | 'completed' | 'failed' | 'cancelled';
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          wallet_id?: string;
          type?: 'credit' | 'debit';
          category?: 'ride_payment' | 'wallet_topup' | 'refund' | 'bonus' | 'cashback' | 'ride_coins_redemption';
          amount?: number;
          ride_coins_change?: number;
          carbon_credits_change?: number;
          description?: string;
          reference_id?: string | null;
          payment_method?: 'cash' | 'upi' | 'card' | 'wallet' | 'crypto';
          transaction_id?: string | null;
          status?: 'pending' | 'completed' | 'failed' | 'cancelled';
          metadata?: any;
          created_at?: string;
        };
      };
      offers: {
        Row: {
          id: string;
          title: string;
          description: string;
          offer_type: 'percentage' | 'fixed_amount' | 'ride_coins' | 'first_ride_free';
          discount_value: number;
          discount_percentage: number;
          max_discount: number | null;
          min_ride_amount: number;
          promo_code: string;
          usage_limit: number | null;
          usage_count: number;
          user_usage_limit: number;
          applicable_ride_types: string[];
          applicable_cities: string[] | null;
          is_active: boolean;
          valid_from: string;
          valid_until: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          offer_type: 'percentage' | 'fixed_amount' | 'ride_coins' | 'first_ride_free';
          discount_value?: number;
          discount_percentage?: number;
          max_discount?: number | null;
          min_ride_amount?: number;
          promo_code: string;
          usage_limit?: number | null;
          usage_count?: number;
          user_usage_limit?: number;
          applicable_ride_types?: string[];
          applicable_cities?: string[] | null;
          is_active?: boolean;
          valid_from?: string;
          valid_until: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          offer_type?: 'percentage' | 'fixed_amount' | 'ride_coins' | 'first_ride_free';
          discount_value?: number;
          discount_percentage?: number;
          max_discount?: number | null;
          min_ride_amount?: number;
          promo_code?: string;
          usage_limit?: number | null;
          usage_count?: number;
          user_usage_limit?: number;
          applicable_ride_types?: string[];
          applicable_cities?: string[] | null;
          is_active?: boolean;
          valid_from?: string;
          valid_until?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      validate_offer_usage: {
        Args: {
          p_user_id: string;
          p_offer_id: string;
          p_ride_amount: number;
        };
        Returns: any;
      };
    };
  };
}